name:                gelbooru-scrape
version:             1.1.0.0
github:              "BlackSoulSeller/gelbooru-scrape"
license:             MIT
author:              "Marcin Czerwonka"
maintainer:          "mcmarcinoser5@gmail.com"
copyright:           "2020 Marcin Czerwonka"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/BlackSoulSeller/gelbooru-scrape#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- parallel-io
- http-conduit
- directory

library:
  source-dirs: src

executables:
  gelbooru-scrape-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gelbooru-scrape

# tests:
#   gelbooru-scrape-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - gelbooru-scrape
